# /api/settings
POST http://0.0.0.0:5000/api/settings
accept: */*
Authorization: Bearer
Content-Type: application/json

{
  "buildCommand": "npm run build",
  "mainBranch": "master",
  "period": 20,
  "repoName": "mikhin/mikhin.github.io"
}

###

# /builds/:commitHash
POST http://0.0.0.0:5000/api/builds/b2cd033a9d5203d2cf1d64e426efd53554ec6de5
accept: */*
Authorization: Bearer
Content-Type: application/json

{
  "commitMessage": "1",
  "commitHash": "233ee840255a82c6d8d5f6dcb9819cf4da289663",
  "branchName": "master",
  "authorName": "yuri"
}

###

# /builds/:buildId/start
POST http://0.0.0.0:5000/api/builds/9989698b-393c-435c-ace2-7e728da3f04f/start
accept: */*
Authorization: Bearer

###

# /builds/:buildId/finish
POST http://0.0.0.0:5000/api/builds/db31e0f2-8b6d-4a47-9b2f-e38f2856b49f/finish
accept: */*
Authorization: Bearer

###

# curl -X DELETE http://localhost:5000/api/settings
DELETE http://localhost:5000/api/settings

###

